### ISSUE TITLE
Feature Request: Download links for OTD Plugin Manager plugins

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver.Web#2]
Sometimes internet isn't directly available to OTD (either because of GitHub API issues, user firewalling OTD, etc), which means that some users are unable to use OTD's plugin manager, and therefore can't easily install plugins without having helpers provide them with links.

Therefore I propose the list of plugins from OTD's Plugin Manager being made available in some form, so that users can easily download plugins outside of OTD's Plugin Manager.

**Comment by gonX** [comment]
Forgot to add: [discord context link](https://discord.com/channels/615607687467761684/615607687467761690/866468079163932693)
(not edited in because then it doesn't show up in our Discord bot)

**Comment by InfinityGhost** [comment]
Resolved in 2be10d00061ac1c62c7be14c179bbbe679568f78
