### ISSUE TITLE
Consider hiding or obscuring linux-x64.tar.gz build

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver.Web#20]
There's a chance Linux newbies will grab the generic Linux package instead of the .deb. Likewise we should probably link to the relevant package for other distros, e.g. AUR.

The generic package should only be used as a last resort IMO.

**Comment by NyaomiDEV** [comment]
I think that this would be problematic for people who want easy access to the latest builds of the software.

Please remember that:
- No one is guaranteed to have the last version of the package in their distro's repos;
- No one is guaranteed to even have the package in their distro's repos in the first place.

**Comment by gonX** [comment]
Thanks for the input.

I am not proposing that we stop providing it, only that we hide it from the website with a clause like "Other versions __here__" or something along those lines, since it's a significant minority of the Linux users that use these.

We have .rpm, .deb and Arch AUR packages which covers a lot of the Linux desktop ecosystem. These should be linked to before the generic build.

**Comment by jamesbt365** [comment]
With the new design of the website this is less of a concern for the website itself.

**Comment by gonX** [comment]
Whoops, good point. That's actually good enough for me. Closing.
