### ISSUE TITLE
Download has bad skeuomorphism

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver.Web#46]
![https://media.discordapp.net/attachments/615611007951306863/933136684177051728/unknown.png](https://media.discordapp.net/attachments/615611007951306863/933136684177051728/unknown.png)

"View On Github" should be changed to a text hyperlink so people are less likely to default to that

And then the actual OS "buttons" should have a border on them that makes them look clickable instead.

**Comment by jamesbt365** [comment]
This is better on the current site now?
![image](https://user-images.githubusercontent.com/22662856/167317869-6230cb49-003b-4f09-a137-24c47ae5762f.png)

**Comment by gonX** [comment]
Yeah I don't mind the current state. We can revisit it later if users are getting confused with the current setup shown in the screenshot by jamesbt365
