### ISSUE TITLE
Address technical mistake in raw input section

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver.Web#58]
Currently it says:
> OpenTabletDriver uses the Windows SendInput API to position the cursor from user level permissions.
It does not move the cursor in a method that raw input accepts as standard cursor movement. 

~~IMO, for accuracys sake it should probably say something in the lines of:~~
> ~~OpenTabletDriver uses the Windows SendInput API to position the cursor from user level permissions, for the most part bypassing the kernel. Raw input is a kernel API and is therefore not usable with OpenTabletDriver unless VMulti is used.~~

With VoiD's correction it should instead be something like:
> OpenTabletDriver has since v0.4.0 supported Raw Input as it uses the Windows `SendInput` API to position the cursor. If you are having tablet cursor issues disable "Map raw input area to screen"[name?]

**Comment by X9VoiD** [comment]
`SendInput` supports `RawInput`. It's the reason why we moved from `SetCursorPos` to `SendInput`. See [#241](https://github.com/OpenTabletDriver/OpenTabletDriver/pull/241).

**Comment by gonX** [comment]
Thanks. I've updated the OP to have significantly different wording
