### ISSUE TITLE
Setup on KDE Plasma X11

### ISSUE THREAD

**Issue by mechan1sm** [OpenTabletDriver/OpenTabletDriver.Web#66]
KDE Plasma doesn't recognize OTD virtual devices as tablet devices by default.
It recognizes them as joystick instead. As a result, you get the permanent acceleration for relative mode.

### To solve this problem:
Run kcminit command every session you want to acceleration to be disabled
Select relative mode in otd-gui and check `xinput list` command output.
You should get strings like these:
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
...
⎜   ↳ OpenTabletDriver Virtual Mouse          	id=18	[slave  pointer  (2)]
...
```
The table below shows which device belongs to which operating mode:
|xinput device| operating mode |
|-----------|-----------|
| OpenTabletDriver Virtual Tablet | absolute |
| OpenTabletDriver Virtual Artist Tablet | artist |
| OpenTabletDriver Virtual Mouse | relative |

Let's see props of virtual mouse device:
```
$ xinput list-props 'OpenTabletDriver Virtual Mouse'
Device 'OpenTabletDriver Virtual Mouse':
	Device Enabled (155):	1
	Coordinate Transformation Matrix (157):	1.000000, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 0.000000, 1.000000
        ...
	libinput Accel Speed (291):	0.000000
	libinput Accel Speed Default (292):	0.000000
	libinput Accel Profiles Available (293):	1, 1
	libinput Accel Profile Enabled (294):	1, 0
	libinput Accel Profile Enabled Default (295):	1, 0
        ...
```
The prop we need to change is `libinput Accel Profile Enabled`
So, let's just change it:
```
xinput set-prop 'OpenTabletDriver Virtual Mouse' 'libinput Accel Profile Enabled' 0, 1
```
And here you are, now you have disabled acceleration for current KDE session.

**Comment by InfinityGhost** [comment]
> Run kcminit command every session you want to acceleration to be disabled

This seems like plasma is supposed to do this already? I personally use GNOME so I can't verify anything like that however.

**Comment by jamesbt365** [comment]
This should be fixed by local changes within OpenTabletDriver, and should be present either in the next update or 0.7. Closing for now until I hear otherwise.
