### ISSUE TITLE
More clear driver installation instrucions on Arch Linux/Manjaro

### ISSUE THREAD

**Issue by PolyCatGamedev** [OpenTabletDriver/OpenTabletDriver.Web#71]
I found it kinda hard to blacklist the drivers that I needed. I was thinking about making a more clear step by step tutorial for installing the driver. I had no problem on Debian/Ubuntu but the Arch Linux Instructions have some commands missing. Also some info about whats happening would be nice. 
I made a file that can be like a prototype, i guess. It can go something like this:

Opentabletdriver Installation for Arch Linux/Manjaro

First you need the "yay" AUR helper.
If you don't have it installed, here's a guide: https://www.debugpoint.com/2021/01/install-yay-arch/ https://www.debugpoint.com/2021/01/install-yay-arch/
And here's where you can learn what a AUR helper is if you don know: https://wiki.archlinux.org/title/AUR_helpers

1.After you installed “yay” run this command and install the package:

yay opentabletdriver-git

2.These commands will blacklist (disable) other drivers in the background that interfere with the program:

echo "blacklist wacom" | sudo tee -a /etc/modprobe.d/blacklist.conf
echo "blacklist hid_uclogic" | sudo tee -a /etc/modprobe.d/blacklist.conf

3.Run these commands to stop the services that were blacklisted:

sudo rmmod wacom
sudo rmmod hid_uclogic

4.And finally run these 2 commands to start the demon (a background app):

systemctl --user daemon-reload
systemctl --user enable opentabletdriver --now

**Comment by gonX** [comment]
Arch packages typically do not autoconfigure themselves like this.

If you follow the PKGBUILD install notes (which are printed when you install it), it does quite clearly tell you to blacklist your existing module.

**Comment by PolyCatGamedev** [comment]
I was talking to add this to the arch linux installation guide on your page. [https://opentabletdriver.net/Wiki/Install/Linux](url)

**Comment by PolyCatGamedev** [comment]
Something like this.
![Screenshot from 2022-05-11 13-12-47](https://user-images.githubusercontent.com/88086950/167826765-347c9819-db76-4be1-af00-f92c2e36358c.png)
