### ISSUE TITLE
Missing documentation for "Multi-Key Binding"

### ISSUE THREAD

**Issue by MicrochipQ** [OpenTabletDriver/OpenTabletDriver.Web#98]
I am faced with a problem while setting up multi-key bindings. It took me a long time to find a piece of code and read it. So I found out:
- Split-symbol for multiple keys should be only "+" and nothing else. [^1] ("ctrl-z", "c-z", "control z", etc. won't work)
- That's all is case-sensitive [^1][^2]
- "Control" is not aliased to "ctrl" or anything like that [^2]

Then I guess adding documentation will save a lot of time for many people.

[^1]: https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/OpenTabletDriver.Desktop/Binding/MultiKeyBinding.cs#L50
[^2]: https://github.com/OpenTabletDriver/OpenTabletDriver/blob/master/OpenTabletDriver.Desktop/Interop/Input/Keyboard/LinuxKeysProvider.cs

**Comment by jamesbt365** [comment]
Don't try and manually set the binding in the advanced binding editor when you don't need to then.

https://user-images.githubusercontent.com/22662856/187661151-a888bcb9-5378-49b1-9ea5-688457b17997.mp4

Documenting user error isn't needed in this case though making it clearer in the ui might be required.
